# 🇧🇷 Jogo da Forca SIMPLES por Vasilikossz:
    # 100% autoral (exceto palavras parcialmente geradas por IA ;
    # (IAs são muito burras pra contar letras, diferenciar palavras com acento e essas besteiras, então,
        # mais da metade das palavras eu tive que mudar));
    # Não precisa mudar nada, só jogakkkkk;
    # Ah, e NÃO USE esse código no Thonny, para melhor experiência.

# 🇺🇸 Simple Hangman Game by Vasilikossz:
    # 100% original (except for words partially generated by AI);
    # (AIs are 2 dumb to count letters, differentiate words with accents and that kind of nonsense, so,
        # I had to change more than half of the words);
    # No need to change anything, just play haha;
    # Oh, and DO NOT USE this code on Thonny, for a better experience.
    
# Bibliotecas importadas (Imported libraries)

import os, random, time

# Variáveis (Variables)

mode, level, word, lagain, letters, underlines, usedL = '', '', '', '', [], [], []
notL, counter_pt, counter_en = 0, 0, 0

# Funções (Functions)

def clears():
    os.system('cls' if os.name == 'nt' else 'clear')

def start():
    print("Simple Hangman Game by Vasilikossz\nWhich language would you like to play in?\nPress 'P' to play in Portuguese, or 'E' to play in English")
    global mode
    mode = input().upper()

def startm_pt():
    print("Qual modo você deseja jogar?\nPressione 'I' se quiser jogar o Modo Iniciante, 'M' para Médio, 'D' para Difícil, e 'E' para Expert.")
    print('''Observações:
1.Não há palavras com cedilha no jogo;
2. Não há nomes próprios;
3. Não há verbos conjugados;
4. Não há palavras no plural.''')
    
    global level
    level = input().upper()

def startm_en():
    print('''Which mode do you want to play?
Press 'S' if you want to play in Starter level, 'A' for Average, 'H' for Hard, and 'E' for Expert.''')
    print('''Notes:
1. There are no proper nouns.
2. There are no conjugated verbs.
3. There are no plural words.''')
    global level
    level = input().upper()

def tryagain_pt():
    global lagain, word, counter_pt
    clears()
    print('''Deseja tentar novamente na mesma dificuldade, ou deseja alterá-la?
Se sim, digite 'S'. Se caso quiser alterar, digite 'N'.''')
    lagain = input().upper()
    if lagain == "N" :
        usedL.clear()
        underlines.clear()
        letters.clear()
        word = ''
        startm_pt()
    elif lagain == "S" :
        usedL.clear()
        underlines.clear()
        letters.clear()
        word = ''
        game()
    else:
        clears()
        print("Opção inválida, tente novamente.")
        counter_pt += 1
        if counter_pt >= 3:
            print("Muitas tentativas inválidas. Encerrando jogo.")
            exit("Jogo encerrado!")
        time.sleep(0.5)
        clears()
        tryagain_pt()

def tryagain_en():
    global lagain, word, counter_en
    clears()
    time.sleep(0.5)
    print('''Do you want to try again at the same difficulty, or do you want to change it?
If yes, type 'Y'. If you want to change it, type 'N'.''')
    lagain = input().upper()
    if lagain == "N" :
        usedL.clear()
        underlines.clear()
        letters.clear()
        word = ''
        startm_en()
    elif lagain == "Y" :
        usedL.clear()
        underlines.clear()
        letters.clear()
        word = ''
        game()
    else:
        clears()
        print("Invalid option, please try again.")
        counter_en += 1
        if counter_en >= 3 :
            print("Too many invalid attempts. Ending game.")
            exit("Game ended!")
        time.sleep(0.5)
        clears()
        tryagain_en()

def playpt():
    global word, letters, underlines
    usedL.clear()
    underlines.clear()
    letters.clear()
    word = ''
    clears()
    time.sleep(0.5)
    startm_pt()
    
    if level == "I": 
        clears()
        time.sleep(0.5)
        print("Você escolheu o Modo Iniciante!")
        time.sleep(0.5)
        clears()
        time.sleep(0.5)
        word = random.choice(pt_starter)
        letters = list(word.upper())
        underlines = list("_"*len(letters))
    
    elif level == "M": 
        clears()
        print("Você escolheu o Modo Médio!")
        time.sleep(0.5)
        clears()
        time.sleep(0.5)
        word = random.choice(pt_average)
        letters = list(word.upper()) 
        underlines = list("_"*len(letters))

    elif level == "D":
         clears()
         print("Você escolheu o Modo Difícil!")
         time.sleep(0.5)
         clears()
         time.sleep(0.5)
         word = random.choice(pt_hard)
         letters = list(word.upper()) 
         underlines = list("_"*len(letters))
        
    elif level == "E":
        clears()
        print("Você escolheu o Modo Expert!")
        time.sleep(0.5)
        clears()
        time.sleep(0.5)
        word = random.choice(pt_expert)
        letters = list(word)
        underlines = list("_"*len(letters))
        

    else:
        clears()
        print(f"{level} não é um modo válido, tente novamente.")
        time.sleep(0.5)
        startm_pt()
    clears()
    time.sleep(0.5)
    game()

def playen():
    global word, letters, underlines
    usedL.clear()
    underlines.clear()
    letters.clear()
    word = ''
    clears()
    time.sleep(0.5)
    startm_en()
    
    if level == "S":
        clears()
        print("You chose Starter Mode!")
        time.sleep(0.5)
        clears()
        word = random.choice(en_starter)
        letters = list(word.upper())
        underlines = list("_"*len(letters))
         

    elif level == "A": 
        clears()
        print("You chose Average Mode!")
        time.sleep(0.5)
        clears()
        word = random.choice(en_average)
        letters = list(word.upper())
        underlines = list("_"*len(letters))
         

    elif level == "H":
        clears()
        print("You chose Hard Mode!")
        time.sleep(0.5)
        clears()
        word = random.choice(en_hard)
        letters = list(word.upper())
        underlines = list("_"*len(letters))
         

    elif level == "E":
        clears()
        print("You chose Expert Mode!")
        time.sleep(0.5)
        clears()
        word = random.choice(en_expert)
        letters = list(word.upper())
        underlines = list("_"*len(letters))
         
    
    else:
        clears()
        print(f"{level} is not a valid mode, please try again.")
        startm_en()
    clears()
    time.sleep(0.5)
    game()

def game():
    tries = 6
    global lagain
    if mode == "P" :
        while underlines != letters and tries > 0:
            print(f"A palavra tem {len(letters)} letras!")
            print("Palavra:", *underlines)
            print("Tentativas restantes:", tries)
            print("Letras usadas:", *usedL)
            l = input("Digite uma letra: ").upper()
            if l in usedL :
                print("Você já usou essa letra! Tente outra.")
                continue
            else:
                usedL.append(l.upper())
            if l.isalpha():
                if l in letters:
                    for i, letter in enumerate(letters):
                        if l == letter:
                            underlines[i] = l
                else:
                    tries -= 1
            else: 
                print("Letra inválida, tente novamente.")
                tries -= 1
                continue
            if tries == 0 :
                print(f"A palavra era: {word}!")
                print("Que pena.. Você perdeu! Tente novamente!")
                print('''Quer tentar novamente?
Se sim, digite 'S'. Se não, digite 'N'.''')
                lagain = input().upper()
                if lagain == "N": 
                    exit("Jogo encerrado!")
                elif lagain == "S" :
                    tryagain_pt()         

    elif mode == "E" :
        while underlines != letters and tries > 0:
            print(f"The word has {len(letters)} letters!")
            print("Word:", *underlines)
            print("Remaining attempts:", tries)
            print("Letters used:", *usedL)
            l = input("Type a letter: ").upper()

            if l in usedL :
                print("You already used this letter! Try another one.")
                continue
            else:
                usedL.append(l.upper()) 
            if l.isalpha():
                if l in letters:
                    for i, letter in enumerate(letters):
                        if l == letter:
                            underlines[i] = l
                else:
                    tries -= 1
            else: 
                print("Invalid letter, please try again.")
                continue
            if tries == 0 :
                print(f"The word was: {word}")
                print("Too bad... You lost! Try again!")
                print('''Do you want to try again?
If yes, type 'Y'. If no, type 'N'.''')
                lagain = input().upper()
                if lagain == "N": 
                    exit("Game over!")
                elif lagain == "Y" :
                    tryagain_en()

    if underlines == letters and mode == "P":
        print(f"Parabéns! Você acertou! A palavra é {word.title()}!")
        time.sleep(0.5)
    elif underlines == letters and mode == "E":
        print(f"Congratulations! You got it right! The word is {word.title()}!")
        time.sleep(0.5)

# --------------------------------------------------------------------------
# --------------------------------------------------------------------------

# Lista de palavras (List of words)

 # Português (Portuguese)

# 🟢 Nível Iniciante em Português [3 a 6 letras] (🟢 Starter Level in Portuguese [3 to 6 letters])
pt_starter = [
"sol", "lua", "rio", "mar", "flor", "vida", "amor", "paz", "fogo", "nuvem",
"casa", "livro", "peixe", "vento", "folha", "chave", "rocha", "amigo", "estrela", "janela"
]

# 🟡 Nível Médio em Português [7 a 9 letras] (🟡 Average level in Portuguese [7 to 9 letters])
pt_average = [
"montanha", "girassol", "garrafa", "alegria", "palavra", "jornada", "mistura", "sabedoria", "tempestade", "passagem",
"lanterna", "liberdade", "aventura", "noturno", "brilhante", "floresta", "oceano", "maravilha", "descoberta", "fantasia"
]

# 🔴 Nível Difícil em Português [10 a 13 letras] (🔴 Hard Level in Portuguese [10 to 13 letters])
pt_hard = [
"curiosidade", "campainha", "luminosidade", "criatividade", "contemplativo", "arqueologia", "simplicidade", "biodiversidade",
"deslumbrante", "poltrona", "conhecimento", "candelabro", "assassinato", "travessia", "responsabilidade", "engenharia",
"universo", "artesanato", "felicidade", "estrategista"
]

# ⚫ Nível Expert em Português [14 a 20 letras] (⚫ Expert level in Portuguese [14 to 20 letters])
pt_expert = [
"anticoncepcional", "desenvolvimento", "autenticidade", "extraoficialmente", "contrarreforma",
"superproporcionado", "transcontinental", "protagonismo", "responsabilidade", "hiperconectividade",
"interdisciplinar", "anticonstitucional", "subdesenvolvido", "comunicacional", "impressionante",
"hiperatividade", "conscientemente", "reestruturamento", "sobrecarregamento", "multidisciplinar"
]

# Inglês (English)

# 🟢 Nível Iniciante em Inglês [3 a 6 letras] (🟢 Starter Level in English [3 to 6 letters])
en_starter = (
"cat", "dog", "sun", "tree", "book", "house", "river", "cloud", "chair", "light", "apple", "smile", "water", "bread", 
"happy", "music", "green", "stone", "plane", "train", "mouse", "flower", "dream", "heart", "phone"
)

# 🟡 Nível Médio em Inglês [7 a 9 letras] (🟡 Average level in English [7 to 9 letters])
en_average = (
"mountain", "elephant", "triangle", "computer", "dinosaur", "butterfly", "sandwich", "painting", "language", "notebook",
"umbrella", "adventure", "chocolate", "backpack", "festival", "beautiful", "diamond", "hospital", "strategy", "invisible",
"calendar", "discovery", "fantastic", "alligator", "important"
)

# 🔴 Nível Difícil em Inglês [10 a 13 letras] (🔴 Hard Level in English [10 to 13 letters])
en_hard = (
"imagination", "environment", "relationship", "extraordinary", "conversation", "understanding", "responsibility", "psychology",
"mathematics", "communication", "consequence", "development", "friendship", "appreciation", "management", "transportation",
"infrastructure", "technology", "organization", "presentation", "international", "opportunity", "conservation",
"determination", "circumference"
)

# ⚫ Nível Expert em Inglês [14 a 20 letras] (⚫ Expert level in English [14 to 20 letters])
en_expert = (
"unquestionable", "incompatibility", "disproportionate", "misinterpretation", "counterproductive", "oversimplification",
"intercontinental", "environmentalist", "hyperconnectivity", "reindustrialization", "miscommunication", "counterintelligence",
"unconstitutional", "extraordinarily", "uncharacteristic", "interdisciplinary", "misunderstanding", "counterterrorism",
"disenfranchisement", "multidimensional", "overrepresentation", "reconceptualization", "interrelationship",
"uncontrollability", "superconductivity"
)

# Início (Start)

while True:
    start()
    if mode == "P":
        clears()
        print("Você escolheu jogar em Português!")
        time.sleep(0.5)
        playpt()
        break
    elif mode == "E":
        clears()
        print("You chose to play in English!")
        time.sleep(0.5)
        playen()
        break
    elif mode == "Q":  # Novo atalho opcional pra sair
        print("Saindo do jogo...")
        time.sleep(0.5)
        break
    else:
        print("Invalid language, please try again.")
        notL += 1
        if notL >= 3:
            print("Muitas tentativas inválidas. Encerrando jogo.")
            break
        time.sleep(0.5)
        clears()


# “Todos nascemos originais, mas muitos de nós morremos como fotocópias.”.. seja diferente!